'use strict';

module.exports = {
  JURISDICTIONS: {
    TORONTO: 'TORONTO'
  },

  GEO_ENTITIES: {
    TORONTO: {
      VOTING_LOCATION: 'TORONTO.VOTE_LOC',
      CITY_POLL: 'TORONTO.POLL',
      CITY_WARD: 'TORONTO.WARD',
      TDSB_WARD: 'TORONTO.TDSB_WARD',
      NEIGHBOURHOOD: 'TORONTO.NEIGHBOURHOOD',
      FORMER_MUNICIPALITY: 'TORONTO.FORMER_MUNICIPALITY'
    }
  },

  GEO_ENTITY_TYPES: {
    MICRO: 'MICRO',
    MACRO: 'MACRO'
  }
};
